<?php

require_once('../tcpdf/tcpdf.php');
include_once '../db_config.php';

$test_id = $_GET['test_id'] ?? null;

if(!$test_id){
    die("Test ID missing");
}

$sql = "
SELECT 
    p.Name,
    p.Patient_ID,
    p.NIC,
    p.Date_of_birth,
    t.Average_positive_probability,
    t.Average_negative_probability,
    t.clinical_comment,
    t.record_date
FROM Test_record t
JOIN patient p ON p.Patient_ID = t.Patient_ID
WHERE t.Test_id = ?
";

$stmt = $conn->prepare($sql);
$stmt->execute([$test_id]);
$data = $stmt->fetch(PDO::FETCH_ASSOC);

if(!$data){
    die("Report data not found");
}

$age = "-";

if(!empty($data['Date_of_birth'])){
    $dob = new DateTime($data['Date_of_birth']);
    $today = new DateTime();
    $age = $today->diff($dob)->y;
}

$pos = round($data['Average_positive_probability'] * 100,2);
$neg = round($data['Average_negative_probability'] * 100,2);

$result = ($pos > 50) ? "POSITIVE (High Risk)" : "NEGATIVE (Low Risk)";

$pdf = new TCPDF();
$pdf->SetTitle('COPD Diagnostic Report');
$pdf->AddPage();

$html = '

<style>

.header{
background-color:#3f5f85;
color:white;
padding:15px;
text-align:center;
}

.subheader{
font-size:12px;
}

.section{
background-color:#eef3f8;
padding:6px;
font-weight:bold;
color:#3f5f85;
margin-top:15px;
}

.table{
border-collapse:collapse;
width:100%;
}

.table td{
border:1px solid #cfd6df;
padding:6px;
vertical-align:middle;
}

.result-box{
background-color:#f2f6fb;
border:1px solid #cfd6df;
padding:10px;
}

.footer{
text-align:center;
font-size:10px;
color:#777;
margin-top:10px;
}

</style>

<div class="header">
<h2>COPD Detection System</h2>
<div class="subheader">Diagnostic Report</div>
</div>

<br>

<div class="section">Patient Information</div>

<br>

<table class="table" width="100%">

<tr>
<td width="35%"><b>Patient Name</b></td>
<td width="65%">'.$data['Name'].'</td>
</tr>

<tr>
<td><b>Patient ID</b></td>
<td>'.$data['Patient_ID'].'</td>
</tr>

<tr>
<td><b>Age</b></td>
<td>'.$age.'</td>
</tr>

<tr>
<td><b>NIC</b></td>
<td>'.$data['NIC'].'</td>
</tr>

<tr>
<td><b>Test Date</b></td>
<td>'.$data['record_date'].'</td>
</tr>

</table>
<br><br><br><br><br>

<div class="section">Diagnostic Summary</div>

<div class="result-box">

<table class="table" width="100%">

<tr>
<td width="70%"><b>Average Positive Probability</b></td>
<td width="30%">'.$pos.' %</td>
</tr>

<tr>
<td width="70%"><b>Average Negative Probability</b></td>
<td width="30%">'.$neg.' %</td>
</tr>

<tr>
<td width="70%"><b>Diagnosis Result</b></td>
<td width="30%"><b>'.$result.'</b></td>
</tr>

</table>
</div>

<br><br><br><br>

<div class="section">Clinical Comment</div>

<div class="result-box">
'.$data['clinical_comment'].'
</div>

<br><br>

<br><br><br><br><br><br><br><br><br>
<br><br>

<table width="100%">

<tr>

<td width="50%">
Doctor Signature : ______________________
</td>

<td width="50%" align="right">
Date : '.date("Y-m-d").'
</td>

</tr>

</table>

<br>

<div class="footer">
Generated by COPD Detection System
</div>

';

$pdf->writeHTML($html, true, false, true, false, '');

$pdf->Output('COPD_Report_'.$test_id.'.pdf', 'I');

?>